apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: alcohol-service
      docker:
        dockerfile: alcohol-service/Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - deploy.yml